//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.ws.clients.preingreso.session;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "WsSesion", targetNamespace = "http://preingreso.metlife.cl/", wsdlLocation = "http://10.77.48.122:8080/WsSesion.asmx?wsdl")
public class WsSesion
    extends Service
{

    private final static URL WSSESION_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cl.metlife.ws.clients.preingreso.session.WsSesion.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cl.metlife.ws.clients.preingreso.session.WsSesion.class.getResource(".");
            url = new URL(baseUrl, "http://10.77.48.122:8080/WsSesion.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.77.48.122:8080/WsSesion.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSSESION_WSDL_LOCATION = url;
    }

    public WsSesion(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsSesion() {
        super(WSSESION_WSDL_LOCATION, new QName("http://preingreso.metlife.cl/", "WsSesion"));
    }

    /**
     * 
     * @return
     *     returns WsSesionSoap
     */
    @WebEndpoint(name = "WsSesionSoap")
    public WsSesionSoap getWsSesionSoap() {
        return super.getPort(new QName("http://preingreso.metlife.cl/", "WsSesionSoap"), WsSesionSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsSesionSoap
     */
    @WebEndpoint(name = "WsSesionSoap")
    public WsSesionSoap getWsSesionSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://preingreso.metlife.cl/", "WsSesionSoap"), WsSesionSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns WsSesionSoap
     */
    @WebEndpoint(name = "WsSesionSoap12")
    public WsSesionSoap getWsSesionSoap12() {
        return super.getPort(new QName("http://preingreso.metlife.cl/", "WsSesionSoap12"), WsSesionSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsSesionSoap
     */
    @WebEndpoint(name = "WsSesionSoap12")
    public WsSesionSoap getWsSesionSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://preingreso.metlife.cl/", "WsSesionSoap12"), WsSesionSoap.class, features);
    }

}
