
package cl.metlife.ws.clients.filenet;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "FileNetWS", targetNamespace = "http://filenet.ws.metlife.cl/", wsdlLocation = "http://mlfprdibmfnet.alico.corp:9080/WsFileNet/FileNetWS/FileNetWS.wsdl")
public class FileNetWS
    extends Service
{

    private final static URL FILENETWS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger((cl.metlife.ws.clients.filenet.FileNetWS.class.getName()));

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cl.metlife.ws.clients.filenet.FileNetWS.class.getResource(".");
            url = new URL(baseUrl, "http://mlfprdibmfnet.alico.corp:9080/WsFileNet/FileNetWS/FileNetWS.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://mlfprdibmfnet.alico.corp:9080/WsFileNet/FileNetWS/FileNetWS.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FILENETWS_WSDL_LOCATION = url;
    }

    public FileNetWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileNetWS() {

        super(FILENETWS_WSDL_LOCATION, new QName("http://filenet.ws.metlife.cl/", "FileNetWS"));
    }

    /**
     * 
     * @return
     *     returns ConectorFileNetWSI
     */
    @WebEndpoint(name = "Filenet")
    public ConectorFileNetWSI getFilenet() {
        return super.getPort(new QName("http://filenet.ws.metlife.cl/", "Filenet"), ConectorFileNetWSI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConectorFileNetWSI
     */
    @WebEndpoint(name = "Filenet")
    public ConectorFileNetWSI getFilenet(WebServiceFeature... features) {
        return super.getPort(new QName("http://filenet.ws.metlife.cl/", "Filenet"), ConectorFileNetWSI.class, features);
    }

}
