//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.ws.clients.pipesponsor;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Dto complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Dto">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://schemas.microsoft.com/2003/10/Serialization/}Id"/>
 *       &lt;attribute ref="{http://schemas.microsoft.com/2003/10/Serialization/}Ref"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dto", namespace = "http://schemas.datacontract.org/2004/07/SmartGear.MetLife.Srp.Application.Seedwork")
@XmlSeeAlso({
    DataMappingDTO.class,
    BusinessObjectDTO.class,
    TargetMappingDataDTO.class,
    SponsorDTO.class,
    FileDescriptionDTO.class,
    FileMappingDTO.class,
    ConditionalEspecDTO.class,
    LogProcessDTO.class,
    ColumnDefinitionDTO.class,
    ColumnMappingDTO.class,
    LegacySystemDTO.class,
    ConditionalSpecSummaryDTO.class,
    FileRelationshipDTO.class,
    BusinessObjectMappingDTO.class,
    LegacyConceptMappingDTO.class,
    OutputEntityDTO.class,
    OutputConnectionDTO.class,
    ColumnDataTypeDTO.class,
    OutputColumnDTO.class,
    StandardConceptDTO.class,
    BusinessObjectFieldDTO.class,
    SessionLogDTO.class,
    ColumnDefinitionLzDTO.class,
    FileOutputColumnsReportDTO.class,
    FileRelationsReportDTO.class,
    FileDescriptionLzDTO.class,
    LogProcessFileDTO.class,
    FileDTO.class,
    LogProcessDataDTO.class,
    ColumnMappingFullInfoDTO.class,
    BusinessObjectFieldLzDTO.class,
    FileReportDTO.class,
    FileRelationshipDescriptorDTO.class,
    SponsorProcessLogDTO.class,
    FileBusinessObjectReportDTO.class
})
public class Dto {

    @XmlAttribute(name = "Id", namespace = "http://schemas.microsoft.com/2003/10/Serialization/")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "Ref", namespace = "http://schemas.microsoft.com/2003/10/Serialization/")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object ref;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getRef() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setRef(Object value) {
        this.ref = value;
    }

}
