//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.ws.clients.pipesponsor;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "SponsorModuleService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://mlfpcdesbo:8080/SrpSrv/SponsorModuleService.svc?wsdl")
public class SponsorModuleService
    extends Service
{

    private final static URL SPONSORMODULESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cl.metlife.ws.clients.pipesponsor.SponsorModuleService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cl.metlife.ws.clients.pipesponsor.SponsorModuleService.class.getResource(".");
            url = new URL(baseUrl, "http://mlfpcdesbo:8080/SrpSrv/SponsorModuleService.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://mlfpcdesbo:8080/SrpSrv/SponsorModuleService.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SPONSORMODULESERVICE_WSDL_LOCATION = url;
    }

    public SponsorModuleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SponsorModuleService() {
        super(SPONSORMODULESERVICE_WSDL_LOCATION, new QName("http://tempuri.org/", "SponsorModuleService"));
    }

    /**
     * 
     * @return
     *     returns ISponsorMouleService
     */
    @WebEndpoint(name = "BasicHttpBinding_ISponsorMouleService")
    public ISponsorMouleService getBasicHttpBindingISponsorMouleService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ISponsorMouleService"), ISponsorMouleService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISponsorMouleService
     */
    @WebEndpoint(name = "BasicHttpBinding_ISponsorMouleService")
    public ISponsorMouleService getBasicHttpBindingISponsorMouleService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ISponsorMouleService"), ISponsorMouleService.class, features);
    }

}
