//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.ws.clients.preingreso.bulk;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sesionId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MovtoAlta" type="{http://preingreso.metlife.cl/}DmMovtoAltaBo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sesionId",
    "movtoAlta"
})
@XmlRootElement(name = "CrearAltaDm")
public class CrearAltaDm {

    protected String sesionId;
    @XmlElement(name = "MovtoAlta")
    protected DmMovtoAltaBo movtoAlta;

    /**
     * Gets the value of the sesionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSesionId() {
        return sesionId;
    }

    /**
     * Sets the value of the sesionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSesionId(String value) {
        this.sesionId = value;
    }

    /**
     * Gets the value of the movtoAlta property.
     * 
     * @return
     *     possible object is
     *     {@link DmMovtoAltaBo }
     *     
     */
    public DmMovtoAltaBo getMovtoAlta() {
        return movtoAlta;
    }

    /**
     * Sets the value of the movtoAlta property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmMovtoAltaBo }
     *     
     */
    public void setMovtoAlta(DmMovtoAltaBo value) {
        this.movtoAlta = value;
    }

}
