//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.ws.clients.preingreso.bulk;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DmMovtoAltaBo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DmMovtoAltaBo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BulkId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="PolizaNumero" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="GrupoNumero" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Titular" type="{http://preingreso.metlife.cl/}DmTitularBo" minOccurs="0"/>
 *         &lt;element name="Carga" type="{http://preingreso.metlife.cl/}DmCargaBo" minOccurs="0"/>
 *         &lt;element name="Observacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TipoPersona" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TipoBeneficiario" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Porcentaje" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="FechaInicioVigencia" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="FechaTerminoVigencia" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Capital" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="Renta" type="{http://preingreso.metlife.cl/}DmRentaBo" minOccurs="0"/>
 *         &lt;element name="Tercero" type="{http://preingreso.metlife.cl/}DmTerceroBo" minOccurs="0"/>
 *         &lt;element name="Cobranza" type="{http://preingreso.metlife.cl/}DmCobranzaBo" minOccurs="0"/>
 *         &lt;element name="Venta" type="{http://preingreso.metlife.cl/}DmVentaBo" minOccurs="0"/>
 *         &lt;element name="PortalRut" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PortalUsuario" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Corredor" type="{http://preingreso.metlife.cl/}DmCorredorBo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DmMovtoAltaBo", namespace = "http://preingreso.metlife.cl/", propOrder = {
    "bulkId",
    "polizaNumero",
    "grupoNumero",
    "titular",
    "carga",
    "observacion",
    "tipoPersona",
    "tipoBeneficiario",
    "porcentaje",
    "fechaInicioVigencia",
    "fechaTerminoVigencia",
    "capital",
    "renta",
    "tercero",
    "cobranza",
    "venta",
    "portalRut",
    "portalUsuario",
    "corredor"
})
public class DmMovtoAltaBo {

    @XmlElement(name = "BulkId")
    protected int bulkId;
    @XmlElement(name = "PolizaNumero")
    protected int polizaNumero;
    @XmlElement(name = "GrupoNumero")
    protected int grupoNumero;
    @XmlElement(name = "Titular")
    protected DmTitularBo titular;
    @XmlElement(name = "Carga")
    protected DmCargaBo carga;
    @XmlElement(name = "Observacion")
    protected String observacion;
    @XmlElement(name = "TipoPersona")
    protected String tipoPersona;
    @XmlElement(name = "TipoBeneficiario")
    protected String tipoBeneficiario;
    @XmlElement(name = "Porcentaje")
    protected int porcentaje;
    @XmlElement(name = "FechaInicioVigencia", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaInicioVigencia;
    @XmlElement(name = "FechaTerminoVigencia", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaTerminoVigencia;
    @XmlElement(name = "Capital", required = true, type = Double.class, nillable = true)
    protected Double capital;
    @XmlElement(name = "Renta")
    protected DmRentaBo renta;
    @XmlElement(name = "Tercero")
    protected DmTerceroBo tercero;
    @XmlElement(name = "Cobranza")
    protected DmCobranzaBo cobranza;
    @XmlElement(name = "Venta")
    protected DmVentaBo venta;
    @XmlElement(name = "PortalRut")
    protected String portalRut;
    @XmlElement(name = "PortalUsuario")
    protected String portalUsuario;
    @XmlElement(name = "Corredor")
    protected DmCorredorBo corredor;

    /**
     * Gets the value of the bulkId property.
     * 
     */
    public int getBulkId() {
        return bulkId;
    }

    /**
     * Sets the value of the bulkId property.
     * 
     */
    public void setBulkId(int value) {
        this.bulkId = value;
    }

    /**
     * Gets the value of the polizaNumero property.
     * 
     */
    public int getPolizaNumero() {
        return polizaNumero;
    }

    /**
     * Sets the value of the polizaNumero property.
     * 
     */
    public void setPolizaNumero(int value) {
        this.polizaNumero = value;
    }

    /**
     * Gets the value of the grupoNumero property.
     * 
     */
    public int getGrupoNumero() {
        return grupoNumero;
    }

    /**
     * Sets the value of the grupoNumero property.
     * 
     */
    public void setGrupoNumero(int value) {
        this.grupoNumero = value;
    }

    /**
     * Gets the value of the titular property.
     * 
     * @return
     *     possible object is
     *     {@link DmTitularBo }
     *     
     */
    public DmTitularBo getTitular() {
        return titular;
    }

    /**
     * Sets the value of the titular property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmTitularBo }
     *     
     */
    public void setTitular(DmTitularBo value) {
        this.titular = value;
    }

    /**
     * Gets the value of the carga property.
     * 
     * @return
     *     possible object is
     *     {@link DmCargaBo }
     *     
     */
    public DmCargaBo getCarga() {
        return carga;
    }

    /**
     * Sets the value of the carga property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmCargaBo }
     *     
     */
    public void setCarga(DmCargaBo value) {
        this.carga = value;
    }

    /**
     * Gets the value of the observacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservacion() {
        return observacion;
    }

    /**
     * Sets the value of the observacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservacion(String value) {
        this.observacion = value;
    }

    /**
     * Gets the value of the tipoPersona property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoPersona() {
        return tipoPersona;
    }

    /**
     * Sets the value of the tipoPersona property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoPersona(String value) {
        this.tipoPersona = value;
    }

    /**
     * Gets the value of the tipoBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoBeneficiario() {
        return tipoBeneficiario;
    }

    /**
     * Sets the value of the tipoBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoBeneficiario(String value) {
        this.tipoBeneficiario = value;
    }

    /**
     * Gets the value of the porcentaje property.
     * 
     */
    public int getPorcentaje() {
        return porcentaje;
    }

    /**
     * Sets the value of the porcentaje property.
     * 
     */
    public void setPorcentaje(int value) {
        this.porcentaje = value;
    }

    /**
     * Gets the value of the fechaInicioVigencia property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaInicioVigencia() {
        return fechaInicioVigencia;
    }

    /**
     * Sets the value of the fechaInicioVigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaInicioVigencia(XMLGregorianCalendar value) {
        this.fechaInicioVigencia = value;
    }

    /**
     * Gets the value of the fechaTerminoVigencia property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaTerminoVigencia() {
        return fechaTerminoVigencia;
    }

    /**
     * Sets the value of the fechaTerminoVigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaTerminoVigencia(XMLGregorianCalendar value) {
        this.fechaTerminoVigencia = value;
    }

    /**
     * Gets the value of the capital property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCapital() {
        return capital;
    }

    /**
     * Sets the value of the capital property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCapital(Double value) {
        this.capital = value;
    }

    /**
     * Gets the value of the renta property.
     * 
     * @return
     *     possible object is
     *     {@link DmRentaBo }
     *     
     */
    public DmRentaBo getRenta() {
        return renta;
    }

    /**
     * Sets the value of the renta property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmRentaBo }
     *     
     */
    public void setRenta(DmRentaBo value) {
        this.renta = value;
    }

    /**
     * Gets the value of the tercero property.
     * 
     * @return
     *     possible object is
     *     {@link DmTerceroBo }
     *     
     */
    public DmTerceroBo getTercero() {
        return tercero;
    }

    /**
     * Sets the value of the tercero property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmTerceroBo }
     *     
     */
    public void setTercero(DmTerceroBo value) {
        this.tercero = value;
    }

    /**
     * Gets the value of the cobranza property.
     * 
     * @return
     *     possible object is
     *     {@link DmCobranzaBo }
     *     
     */
    public DmCobranzaBo getCobranza() {
        return cobranza;
    }

    /**
     * Sets the value of the cobranza property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmCobranzaBo }
     *     
     */
    public void setCobranza(DmCobranzaBo value) {
        this.cobranza = value;
    }

    /**
     * Gets the value of the venta property.
     * 
     * @return
     *     possible object is
     *     {@link DmVentaBo }
     *     
     */
    public DmVentaBo getVenta() {
        return venta;
    }

    /**
     * Sets the value of the venta property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmVentaBo }
     *     
     */
    public void setVenta(DmVentaBo value) {
        this.venta = value;
    }

    /**
     * Gets the value of the portalRut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortalRut() {
        return portalRut;
    }

    /**
     * Sets the value of the portalRut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortalRut(String value) {
        this.portalRut = value;
    }

    /**
     * Gets the value of the portalUsuario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortalUsuario() {
        return portalUsuario;
    }

    /**
     * Sets the value of the portalUsuario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortalUsuario(String value) {
        this.portalUsuario = value;
    }

    /**
     * Gets the value of the corredor property.
     * 
     * @return
     *     possible object is
     *     {@link DmCorredorBo }
     *     
     */
    public DmCorredorBo getCorredor() {
        return corredor;
    }

    /**
     * Sets the value of the corredor property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmCorredorBo }
     *     
     */
    public void setCorredor(DmCorredorBo value) {
        this.corredor = value;
    }

}
