//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.ws.clients.preingreso.bulk;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DmTitularBo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DmTitularBo">
 *   &lt;complexContent>
 *     &lt;extension base="{http://preingreso.metlife.cl/}DmPersonaBo">
 *       &lt;sequence>
 *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CuentaDeposito" type="{http://preingreso.metlife.cl/}DmCuentaDepositoBo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DmTitularBo", namespace = "http://preingreso.metlife.cl/", propOrder = {
    "email",
    "cuentaDeposito"
})
public class DmTitularBo
    extends DmPersonaBo
{

    @XmlElement(name = "Email")
    protected String email;
    @XmlElement(name = "CuentaDeposito")
    protected DmCuentaDepositoBo cuentaDeposito;

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the cuentaDeposito property.
     * 
     * @return
     *     possible object is
     *     {@link DmCuentaDepositoBo }
     *     
     */
    public DmCuentaDepositoBo getCuentaDeposito() {
        return cuentaDeposito;
    }

    /**
     * Sets the value of the cuentaDeposito property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmCuentaDepositoBo }
     *     
     */
    public void setCuentaDeposito(DmCuentaDepositoBo value) {
        this.cuentaDeposito = value;
    }

}
