//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.ws.clients.preingreso.bulk;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SetBo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SetBo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Folio" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="EstadoId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EstadoNombre" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Contratante" type="{http://preingreso.metlife.cl/}ContratanteBo" minOccurs="0"/>
 *         &lt;element name="TipoMovimiento" type="{http://preingreso.metlife.cl/}TipoMovimientoBo" minOccurs="0"/>
 *         &lt;element name="MovtoAltas" type="{http://preingreso.metlife.cl/}ArrayOfMovtoAltaBo" minOccurs="0"/>
 *         &lt;element name="MovtoBajas" type="{http://preingreso.metlife.cl/}ArrayOfMovtoBajaBo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SetBo", namespace = "http://preingreso.metlife.cl/", propOrder = {
    "id",
    "folio",
    "estadoId",
    "estadoNombre",
    "contratante",
    "tipoMovimiento",
    "movtoAltas",
    "movtoBajas"
})
public class SetBo {

    @XmlElement(name = "Id", required = true, type = Integer.class, nillable = true)
    protected Integer id;
    @XmlElement(name = "Folio", required = true, type = Integer.class, nillable = true)
    protected Integer folio;
    @XmlElement(name = "EstadoId")
    protected String estadoId;
    @XmlElement(name = "EstadoNombre")
    protected String estadoNombre;
    @XmlElement(name = "Contratante")
    protected ContratanteBo contratante;
    @XmlElement(name = "TipoMovimiento")
    protected TipoMovimientoBo tipoMovimiento;
    @XmlElement(name = "MovtoAltas")
    protected ArrayOfMovtoAltaBo movtoAltas;
    @XmlElement(name = "MovtoBajas")
    protected ArrayOfMovtoBajaBo movtoBajas;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the folio property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFolio() {
        return folio;
    }

    /**
     * Sets the value of the folio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFolio(Integer value) {
        this.folio = value;
    }

    /**
     * Gets the value of the estadoId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstadoId() {
        return estadoId;
    }

    /**
     * Sets the value of the estadoId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstadoId(String value) {
        this.estadoId = value;
    }

    /**
     * Gets the value of the estadoNombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstadoNombre() {
        return estadoNombre;
    }

    /**
     * Sets the value of the estadoNombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstadoNombre(String value) {
        this.estadoNombre = value;
    }

    /**
     * Gets the value of the contratante property.
     * 
     * @return
     *     possible object is
     *     {@link ContratanteBo }
     *     
     */
    public ContratanteBo getContratante() {
        return contratante;
    }

    /**
     * Sets the value of the contratante property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContratanteBo }
     *     
     */
    public void setContratante(ContratanteBo value) {
        this.contratante = value;
    }

    /**
     * Gets the value of the tipoMovimiento property.
     * 
     * @return
     *     possible object is
     *     {@link TipoMovimientoBo }
     *     
     */
    public TipoMovimientoBo getTipoMovimiento() {
        return tipoMovimiento;
    }

    /**
     * Sets the value of the tipoMovimiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoMovimientoBo }
     *     
     */
    public void setTipoMovimiento(TipoMovimientoBo value) {
        this.tipoMovimiento = value;
    }

    /**
     * Gets the value of the movtoAltas property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfMovtoAltaBo }
     *     
     */
    public ArrayOfMovtoAltaBo getMovtoAltas() {
        return movtoAltas;
    }

    /**
     * Sets the value of the movtoAltas property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfMovtoAltaBo }
     *     
     */
    public void setMovtoAltas(ArrayOfMovtoAltaBo value) {
        this.movtoAltas = value;
    }

    /**
     * Gets the value of the movtoBajas property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfMovtoBajaBo }
     *     
     */
    public ArrayOfMovtoBajaBo getMovtoBajas() {
        return movtoBajas;
    }

    /**
     * Sets the value of the movtoBajas property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfMovtoBajaBo }
     *     
     */
    public void setMovtoBajas(ArrayOfMovtoBajaBo value) {
        this.movtoBajas = value;
    }

}
