//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.ws.clients.preingreso.bulk;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "WsBulkSoap", targetNamespace = "http://preingreso.metlife.cl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsBulkSoap {


    /**
     * 
     * @param nombreAdjunto
     * @param sesionId
     * @param fechaRecepcion
     * @param portalNombre
     * @param portalRut
     * @param tipoMovimiento
     * @param agrupacionCorredor
     * @return
     *     returns cl.metlife.ws.clients.preingreso.bulk.BulkBo
     */
    @WebMethod(operationName = "Crear", action = "http://preingreso.metlife.cl/Crear")
    @WebResult(name = "CrearResult", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "Crear", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.Crear")
    @ResponseWrapper(localName = "CrearResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.CrearResponse")
    public BulkBo crear(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId,
        @WebParam(name = "tipoMovimiento", targetNamespace = "http://preingreso.metlife.cl/")
        int tipoMovimiento,
        @WebParam(name = "nombreAdjunto", targetNamespace = "http://preingreso.metlife.cl/")
        String nombreAdjunto,
        @WebParam(name = "fechaRecepcion", targetNamespace = "http://preingreso.metlife.cl/")
        XMLGregorianCalendar fechaRecepcion,
        @WebParam(name = "portalRut", targetNamespace = "http://preingreso.metlife.cl/")
        String portalRut,
        @WebParam(name = "portalNombre", targetNamespace = "http://preingreso.metlife.cl/")
        String portalNombre,
        @WebParam(name = "agrupacionCorredor", targetNamespace = "http://preingreso.metlife.cl/")
        AgrupacionCorredor agrupacionCorredor);

    /**
     * 
     * @param sesionId
     * @param movto
     * @return
     *     returns cl.metlife.ws.clients.preingreso.bulk.ErrorBo
     */
    @WebMethod(operationName = "CrearAlta", action = "http://preingreso.metlife.cl/CrearAlta")
    @WebResult(name = "CrearAltaResult", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "CrearAlta", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.CrearAlta")
    @ResponseWrapper(localName = "CrearAltaResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.CrearAltaResponse")
    public ErrorBo crearAlta(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId,
        @WebParam(name = "movto", targetNamespace = "http://preingreso.metlife.cl/")
        MovtoAltaBo movto);

    /**
     * 
     * @param sesionId
     * @param movto
     * @return
     *     returns cl.metlife.ws.clients.preingreso.bulk.ErrorBo
     */
    @WebMethod(operationName = "CrearBaja", action = "http://preingreso.metlife.cl/CrearBaja")
    @WebResult(name = "CrearBajaResult", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "CrearBaja", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.CrearBaja")
    @ResponseWrapper(localName = "CrearBajaResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.CrearBajaResponse")
    public ErrorBo crearBaja(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId,
        @WebParam(name = "movto", targetNamespace = "http://preingreso.metlife.cl/")
        MovtoBajaBo movto);

    /**
     * 
     * @param sesionId
     * @param bulkId
     * @return
     *     returns cl.metlife.ws.clients.preingreso.bulk.ErrorBo
     */
    @WebMethod(operationName = "Ejecutar", action = "http://preingreso.metlife.cl/Ejecutar")
    @WebResult(name = "EjecutarResult", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "Ejecutar", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.Ejecutar")
    @ResponseWrapper(localName = "EjecutarResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.EjecutarResponse")
    public ErrorBo ejecutar(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId,
        @WebParam(name = "bulkId", targetNamespace = "http://preingreso.metlife.cl/")
        int bulkId);

    /**
     * 
     * @param sesionId
     * @param bulkId
     * @return
     *     returns cl.metlife.ws.clients.preingreso.bulk.BulkBo
     */
    @WebMethod(operationName = "Info", action = "http://preingreso.metlife.cl/Info")
    @WebResult(name = "InfoResult", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "Info", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.Info")
    @ResponseWrapper(localName = "InfoResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.InfoResponse")
    public BulkBo info(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId,
        @WebParam(name = "bulkId", targetNamespace = "http://preingreso.metlife.cl/")
        int bulkId);

    /**
     * 
     * @param sesionId
     * @param bulkId
     * @return
     *     returns cl.metlife.ws.clients.preingreso.bulk.ArrayOfMovtoErrorBo
     */
    @WebMethod(operationName = "ListarError", action = "http://preingreso.metlife.cl/ListarError")
    @WebResult(name = "ListarErrorResult", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "ListarError", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.ListarError")
    @ResponseWrapper(localName = "ListarErrorResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.ListarErrorResponse")
    public ArrayOfMovtoErrorBo listarError(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId,
        @WebParam(name = "bulkId", targetNamespace = "http://preingreso.metlife.cl/")
        int bulkId);

    /**
     * 
     * @param sesionId
     * @param bulkId
     * @return
     *     returns cl.metlife.ws.clients.preingreso.bulk.ArrayOfSetBo
     */
    @WebMethod(operationName = "ListarSet", action = "http://preingreso.metlife.cl/ListarSet")
    @WebResult(name = "ListarSetResult", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "ListarSet", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.ListarSet")
    @ResponseWrapper(localName = "ListarSetResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.ListarSetResponse")
    public ArrayOfSetBo listarSet(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId,
        @WebParam(name = "bulkId", targetNamespace = "http://preingreso.metlife.cl/")
        int bulkId);

    /**
     * 
     * @param sesionId
     * @param lote
     * @param corredorRutDv
     * @param fechaDesde
     * @param login
     * @param fechaHasta
     * @param setId
     * @param bulkId
     * @return
     *     returns cl.metlife.ws.clients.preingreso.bulk.ArrayOfMovtoBajaBo
     */
    @WebMethod(operationName = "InfoSetBajas", action = "http://preingreso.metlife.cl/InfoSetBajas")
    @WebResult(name = "InfoSetBajasResult", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "InfoSetBajas", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.InfoSetBajas")
    @ResponseWrapper(localName = "InfoSetBajasResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.InfoSetBajasResponse")
    public ArrayOfMovtoBajaBo infoSetBajas(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId,
        @WebParam(name = "bulkId", targetNamespace = "http://preingreso.metlife.cl/")
        Integer bulkId,
        @WebParam(name = "setId", targetNamespace = "http://preingreso.metlife.cl/")
        Integer setId,
        @WebParam(name = "lote", targetNamespace = "http://preingreso.metlife.cl/")
        String lote,
        @WebParam(name = "fechaDesde", targetNamespace = "http://preingreso.metlife.cl/")
        XMLGregorianCalendar fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "http://preingreso.metlife.cl/")
        XMLGregorianCalendar fechaHasta,
        @WebParam(name = "corredorRutDv", targetNamespace = "http://preingreso.metlife.cl/")
        String corredorRutDv,
        @WebParam(name = "login", targetNamespace = "http://preingreso.metlife.cl/")
        String login);

    /**
     * 
     * @param cargaDv
     * @param sesionId
     * @param cargaRut
     * @param fileNetCodigoGrabarResult
     * @param errorNumero
     * @param errorDescripcion
     * @param codigoFileNet
     * @param titularDv
     * @param grupo
     * @param titularRut
     * @param bulkId
     * @param polizaNumero
     */
    @WebMethod(operationName = "FileNetCodigoGrabar", action = "http://preingreso.metlife.cl/FileNetCodigoGrabar")
    @RequestWrapper(localName = "FileNetCodigoGrabar", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.FileNetCodigoGrabar")
    @ResponseWrapper(localName = "FileNetCodigoGrabarResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.FileNetCodigoGrabarResponse")
    public void fileNetCodigoGrabar(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId,
        @WebParam(name = "bulkId", targetNamespace = "http://preingreso.metlife.cl/")
        int bulkId,
        @WebParam(name = "polizaNumero", targetNamespace = "http://preingreso.metlife.cl/")
        int polizaNumero,
        @WebParam(name = "grupo", targetNamespace = "http://preingreso.metlife.cl/")
        int grupo,
        @WebParam(name = "titularRut", targetNamespace = "http://preingreso.metlife.cl/")
        int titularRut,
        @WebParam(name = "titularDv", targetNamespace = "http://preingreso.metlife.cl/")
        int titularDv,
        @WebParam(name = "cargaRut", targetNamespace = "http://preingreso.metlife.cl/")
        Integer cargaRut,
        @WebParam(name = "cargaDv", targetNamespace = "http://preingreso.metlife.cl/")
        Integer cargaDv,
        @WebParam(name = "codigoFileNet", targetNamespace = "http://preingreso.metlife.cl/")
        String codigoFileNet,
        @WebParam(name = "errorNumero", targetNamespace = "http://preingreso.metlife.cl/", mode = WebParam.Mode.INOUT)
        Holder<Integer> errorNumero,
        @WebParam(name = "errorDescripcion", targetNamespace = "http://preingreso.metlife.cl/", mode = WebParam.Mode.INOUT)
        Holder<String> errorDescripcion,
        @WebParam(name = "FileNetCodigoGrabarResult", targetNamespace = "http://preingreso.metlife.cl/", mode = WebParam.Mode.OUT)
        Holder<ErrorBo> fileNetCodigoGrabarResult);

    /**
     * 
     * @param sesionId
     * @param bulkId
     * @return
     *     returns cl.metlife.ws.clients.preingreso.bulk.BulkDetalleBo
     */
    @WebMethod(operationName = "BulkDetalle2", action = "http://preingreso.metlife.cl/BulkDetalle2")
    @WebResult(name = "BulkDetalle2Result", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "BulkDetalle2", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.BulkDetalle2")
    @ResponseWrapper(localName = "BulkDetalle2Response", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.BulkDetalle2Response")
    public BulkDetalleBo bulkDetalle2(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId,
        @WebParam(name = "bulkId", targetNamespace = "http://preingreso.metlife.cl/")
        int bulkId);

    /**
     * 
     * @param sesionId
     * @param fechaDesde
     * @param fechaHasta
     * @param bulkId
     * @return
     *     returns cl.metlife.ws.clients.preingreso.bulk.BulkDetalleBo
     */
    @WebMethod(operationName = "BulkDetalle", action = "http://preingreso.metlife.cl/BulkDetalle")
    @WebResult(name = "BulkDetalleResult", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "BulkDetalle", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.BulkDetalle")
    @ResponseWrapper(localName = "BulkDetalleResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.BulkDetalleResponse")
    public BulkDetalleBo bulkDetalle(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId,
        @WebParam(name = "bulkId", targetNamespace = "http://preingreso.metlife.cl/")
        Integer bulkId,
        @WebParam(name = "fechaDesde", targetNamespace = "http://preingreso.metlife.cl/")
        XMLGregorianCalendar fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "http://preingreso.metlife.cl/")
        XMLGregorianCalendar fechaHasta);

    /**
     * 
     * @param sesionId
     * @param movtoAlta
     * @return
     *     returns cl.metlife.ws.clients.preingreso.bulk.ErrorBo
     */
    @WebMethod(operationName = "CrearAltaDm", action = "http://preingreso.metlife.cl/CrearAltaDm")
    @WebResult(name = "CrearAltaDmResult", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "CrearAltaDm", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.CrearAltaDm")
    @ResponseWrapper(localName = "CrearAltaDmResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.CrearAltaDmResponse")
    public ErrorBo crearAltaDm(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId,
        @WebParam(name = "MovtoAlta", targetNamespace = "http://preingreso.metlife.cl/")
        DmMovtoAltaBo movtoAlta);

    /**
     * 
     * @param sesionId
     * @param movtoBaja
     * @return
     *     returns cl.metlife.ws.clients.preingreso.bulk.ErrorBo
     */
    @WebMethod(operationName = "CrearBajaDm", action = "http://preingreso.metlife.cl/CrearBajaDm")
    @WebResult(name = "CrearBajaDmResult", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "CrearBajaDm", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.CrearBajaDm")
    @ResponseWrapper(localName = "CrearBajaDmResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.bulk.CrearBajaDmResponse")
    public ErrorBo crearBajaDm(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId,
        @WebParam(name = "MovtoBaja", targetNamespace = "http://preingreso.metlife.cl/")
        DmMovtoBajaBo movtoBaja);

}
