//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package cl.metlife.ws.clients.preingreso.bulk;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "WsBulk", targetNamespace = "http://preingreso.metlife.cl/", wsdlLocation = "http://10.77.208.109:8080/WsBulk.asmx?wsdl")
public class WsBulk
    extends Service
{

    private final static URL WSBULK_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cl.metlife.ws.clients.preingreso.bulk.WsBulk.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cl.metlife.ws.clients.preingreso.bulk.WsBulk.class.getResource(".");
            url = new URL(baseUrl, "http://10.77.208.109:8080/WsBulk.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.77.208.109:8080/WsBulk.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSBULK_WSDL_LOCATION = url;
    }

    public WsBulk(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsBulk() {
        super(WSBULK_WSDL_LOCATION, new QName("http://preingreso.metlife.cl/", "WsBulk"));
    }

    /**
     * 
     * @return
     *     returns WsBulkSoap
     */
    @WebEndpoint(name = "WsBulkSoap")
    public WsBulkSoap getWsBulkSoap() {
        return super.getPort(new QName("http://preingreso.metlife.cl/", "WsBulkSoap"), WsBulkSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsBulkSoap
     */
    @WebEndpoint(name = "WsBulkSoap")
    public WsBulkSoap getWsBulkSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://preingreso.metlife.cl/", "WsBulkSoap"), WsBulkSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns WsBulkSoap
     */
    @WebEndpoint(name = "WsBulkSoap12")
    public WsBulkSoap getWsBulkSoap12() {
        return super.getPort(new QName("http://preingreso.metlife.cl/", "WsBulkSoap12"), WsBulkSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsBulkSoap
     */
    @WebEndpoint(name = "WsBulkSoap12")
    public WsBulkSoap getWsBulkSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://preingreso.metlife.cl/", "WsBulkSoap12"), WsBulkSoap.class, features);
    }

}
